import { test, expect } from '@playwright/test';
import { monitorApiCall } from '../utils/apiMonitor';


test('test', async ({ page }) => {
    const checkApi = await monitorApiCall(page, '/api/latest-tools');
  await page.goto('https://s4e.io/free-security-tools');

  await page.getByRole('cell', { name: 'Stack Trace Error Detection Scanner', exact: true }).click();
  await page.goto('https://s4e.io/free-security-tools');
  await page.getByRole('row', { name: 'Stack Trace Error Detection Scanner This scanner detects the use of Stack Trace' }).getByRole('button').click();
  await page.getByRole('cell', { name: 'OOB DNS Interaction Parameter' }).click();
  await page.goto('https://s4e.io/free-security-tools');
  await page.getByLabel('Low').getByRole('button', { name: 'Low' }).click();
  await page.getByRole('cell', { name: 'HTTP Response Time Checker' }).click();
  await page.getByRole('row', { name: 'OOB DNS Interaction Parameter' }).getByRole('button').click();
  await page.getByRole('cell', { name: 'CVE-2024-21641 Scanner', exact: true }).click();
  await page.getByRole('row', { name: 'CVE-2024-38475 Scanner CVE-' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Severity' }).click();
  await page.getByRole('menuitem', { name: 'High' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?severity=high&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('row', { name: 'CVE-2024-13322 Scanner CVE-' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Severity' }).click();
  await page.getByRole('menuitem', { name: 'Medium' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?severity=medium&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('row', { name: 'Stack Trace Error Detection Scanner This scanner detects the use of Stack Trace' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Severity' }).click();
  await page.getByRole('menuitem', { name: 'Low' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?severity=low&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('row', { name: 'Not Found Page Detection Scanner This scanner detects the use of 404 Not Found' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Severity' }).click();
  await page.getByRole('menuitem', { name: 'Informational' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?severity=info&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.locator('#dynamic-filter-popup').click();
  await page.getByRole('button', { name: 'Asset Type' }).click();
  await page.getByRole('menuitem', { name: 'Domain' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?asset_type=domain&page=0');
  await page.getByRole('menuitem', { name: 'IPv4' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?asset_type=ipv4&page=0');
  await page.getByRole('menuitem', { name: 'Email' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?asset_type=email&page=0');
  await page.getByRole('menuitem', { name: 'URL' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?asset_type=url&page=0');
  await page.getByRole('menuitem', { name: 'Request' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?asset_type=request&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Category' }).click();
  await page.getByText('DNS Controls').click();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Asset Type' }).click();
  await page.getByRole('menuitem', { name: 'Request' }).getByRole('radio').check();
  await page.getByRole('menuitem', { name: 'Request' }).getByRole('radio').check();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByRole('button', { name: 'Category' }).click();
  await page.getByRole('menuitem', { name: 'DNS Controls' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=dns-controls&page=0');
  await page.getByRole('menuitem', { name: 'SSL Controls' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=ssl-controls&page=0');
  await page.getByRole('menuitem', { name: 'Misconfiguration' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=misconfiguration&page=0');
  await page.getByRole('menuitem', { name: 'Network Vulnerabilities', exact: true }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=network-vulnerabilities&page=0');
  await page.getByRole('menuitem', { name: 'Web Vulnerabilities', exact: true }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=web-vulnerabilities&page=0');
  await page.getByRole('menuitem', { name: 'Information Scans' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=information-scans&page=0');
  await page.getByRole('menuitem', { name: 'Product Based Web' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=product-based-web-vulnerabilities&page=0');
  await page.getByRole('menuitem', { name: 'Product Based Network' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?tools-category=product-based-network-vulnerabilities&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('tab', { name: 'Asset Owner' }).click();
  await page.getByRole('tab', { name: 'Everyone' }).click();
  await page.getByRole('button', { name: 'Asset Type' }).click();
  await page.getByRole('menuitem', { name: 'Domain' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Severity' }).click();
  await page.getByRole('menuitem', { name: 'Low' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Category' }).click();
  await page.getByRole('menuitem', { name: 'DNS Controls' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=dns-controls');
  await page.getByRole('menuitem', { name: 'SSL Controls' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=ssl-controls');
  await page.getByRole('menuitem', { name: 'Misconfiguration' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=misconfiguration');
  await page.getByRole('menuitem', { name: 'Network Vulnerabilities', exact: true }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=network-vulnerabilities');
  await page.getByRole('menuitem', { name: 'Web Vulnerabilities', exact: true }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=web-vulnerabilities');
  await page.getByRole('menuitem', { name: 'Information Scans' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=information-scans');
  await page.getByRole('menuitem', { name: 'Product Based Web' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=product-based-web-vulnerabilities');
  await page.getByRole('menuitem', { name: 'Product Based Network' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=domain&severity=low&tools-category=product-based-network-vulnerabilities');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Asset Type' }).click();
  await page.getByRole('menuitem', { name: 'IPv4' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?scan_type=everyone&page=0&asset_type=ipv4&severity=low&tools-category=product-based-network-vulnerabilities');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByRole('button', { name: 'Severity' }).click();
  await page.getByRole('menuitem', { name: 'High' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?severity=high&page=0');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('button', { name: 'Asset Type' }).click();
  await page.getByRole('menuitem', { name: 'URL' }).getByRole('radio').check();
  await page.goto('https://s4e.io/free-security-tools?severity=high&page=0&asset_type=url');
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('textbox', { name: 'Search tools name' }).click();
  await page.getByRole('textbox', { name: 'Search tools name' }).fill('cve');
  await page.getByRole('textbox', { name: 'Search tools name' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search tools name' }).fill('');
  await page.getByRole('textbox', { name: 'Search tools name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search tools name' }).fill('CVE');
  await page.getByRole('textbox', { name: 'Search tools name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search tools name' }).fill('qqq');
  await page.goto('https://s4e.io/free-security-tools?severity=high&page=0&asset_type=url&text=qqq');
  await page.getByRole('textbox', { name: 'Search tools name' }).fill('');
  await page.getByRole('button', { name: 'Clear' }).click();
});